version: '2'
services:
     jenkins_test:
        build:
           context: .
           dockerfile: Dockerfile
        volumes:
          - "./app:/app"
          - "./testreports:/testreports"
        command: ["sh", "entry_point.sh"]
